#!/bin/zsh

export AUTO_COMPLETE="/usr/share/nano-tool/"

function find_file() {
    local file_to_find=$1
    local file=$(fd -H "$file_to_find" / | fzf)
    open_nano "$file"
}

function open_nano() {
    local file=$1

    expect -c "
  log_user 0
  spawn nano \"$file\" 
  interact
"
}

function open_nano_and_search() {
    local file=$1
    local search_string=$2

    expect -c "
  log_user 0 
  spawn nano \"$file\" 
  sleep 0.1  
  send \x17  
  send \"$search_string\r\"  
  interact
"
}

function find_and_search() {
    local file_to_find=$1
    local search_string=$2
    local file=$(fd -H "$file_to_find" / | fzf)
    open_nano_and_search "$file" "$search_string"
}

source ${AUTO_COMPLETE}auto_complete_no.zsh

case "$1" in
-f)
    find_file "$2"
    ;;
-s)
    find_and_search "$2" "$3"
    ;;
*)
    echo "Tham số không hợp lệ. Sử dụng -f để tìm file hoặc -s để tìm chuỗi trong file."
    ;;
esac
